/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TESTPB_USER_PB_H_INCLUDED
#define PB_TESTPB_USER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ./generator/nanopb_generator -v -I ./wps -D ./wps ./wps/user.proto
 User 定义了一个用户的基本信息 */
typedef struct _testpb_User {
    int32_t id; /* 用户的唯一ID */
    char name[32]; /* 用户的姓名 */
    char email[64]; /* 用户的电子邮件地址 */
} testpb_User;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define testpb_User_init_default                 {0, "", ""}
#define testpb_User_init_zero                    {0, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define testpb_User_id_tag                       1
#define testpb_User_name_tag                     2
#define testpb_User_email_tag                    3

/* Struct field encoding specification for nanopb */
#define testpb_User_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, STRING,   email,             3)
#define testpb_User_CALLBACK NULL
#define testpb_User_DEFAULT NULL

extern const pb_msgdesc_t testpb_User_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define testpb_User_fields &testpb_User_msg

/* Maximum encoded size of messages (where known) */
#define TESTPB_USER_PB_H_MAX_SIZE                testpb_User_size
#define testpb_User_size                         109

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
