/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "yw_fpa.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ywfpa_PkgHeader, ywfpa_PkgHeader, AUTO)


PB_BIND(ywfpa_CmdHeader, ywfpa_CmdHeader, AUTO)


PB_BIND(ywfpa_DevAdded, ywfpa_DevAdded, AUTO)


PB_BIND(ywfpa_DevRemoved, ywfpa_DevRemoved, AUTO)


PB_BIND(ywfpa_SegmentInfo, ywfpa_SegmentInfo, AUTO)


PB_BIND(ywfpa_SegmentUpdated, ywfpa_SegmentUpdated, AUTO)





