/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_YWFPA_YW_FPA_PB_H_INCLUDED
#define PB_YWFPA_YW_FPA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 命令号 -- 用于区分不同的消息 */
typedef enum _ywfpa_CmdId {
    /* -- 系统组 和TF卡无关命令 */
    ywfpa_CmdId_CmdNA = 0, /* 无效命令 */
    ywfpa_CmdId_CmdAlive = 1, /* 心跳 */
    ywfpa_CmdId_CmdStart = 2, /* 开始 */
    ywfpa_CmdId_CmdExit = 3, /* 退出 */
    /* -- 媒体组 和TF卡有关命令 */
    ywfpa_CmdId_CmdDevAdded = 4, /* 设备初始化 */
    ywfpa_CmdId_CmdDevRemoved = 5, /* 设备移除 */
    ywfpa_CmdId_CmdSegmentUpdated = 6 /* 媒体段信息 -- 更新 */
} ywfpa_CmdId;

/* Struct definitions */
/* ./generator/nanopb_generator -v -I ./pb -D ./pb ./pb/ywfpa.proto
FPA => KO
 包头 -- 固定长度 */
typedef struct _ywfpa_PkgHeader {
    uint32_t magic; /* 魔数 0xFEADBEEF */
    uint32_t cmd; /* 命令号 -- 用于区分不同的消息 */
    uint32_t seq; /* 发起方的 序列号 --- 非0 */
    uint32_t seq_org; /* 应答时，对应应答的 原 序列号 --- 非0 是原请求的 seq. 0 表示不是应答，是请求 */
    int32_t rc; /* 返回码 0:成功，<0:失败, >0: 表示数量 */
    uint32_t context; /* 上下文信息 -- 接收方原样返回 */
} ywfpa_PkgHeader;

/* 设备消息 -- 设备初始化 */
typedef struct _ywfpa_DevAdded {
    bool has_cmd_header;
    ywfpa_PkgHeader cmd_header; /* 包含 Header 消息 */
    uint32_t dev_id; /* 设备 ID, 不管是 TF 还  SSD， 统一排序 */
} ywfpa_DevAdded;

/* 设备消息 -- 设备移除 */
typedef struct _ywfpa_DevRemoved {
    bool has_cmd_header;
    ywfpa_PkgHeader cmd_header; /* 包含 Header 消息 */
    uint32_t dev_id; /* 设备 ID, 不管是 TF 还  SSD， 统一排序 */
} ywfpa_DevRemoved;

/* 媒体段 -- 数据 */
typedef struct _ywfpa_SegmentInfo {
    uint32_t dev_id; /* 设备 ID, 不管是 TF 还  SSD， 统一排序 */
    uint32_t seg_id; /* 媒体段 ID， 与VA中的 Segment ID 一致 */
    uint32_t begin_time; /* 媒体开始时间 2000-01-01 00:00:00开始的UTC时间秒数 --0 表示本段被删除/覆盖 */
    uint32_t end_time; /* 结束时间,2000-01-01 00:00:00开始的UTC时间秒数 -- 0 表示未结束, 仍在录制 */
    uint32_t media_type_mask; /* 媒体类型掩码 见DXR_MDMASK_ALL */
    uint32_t ch_mask; /* 通道掩码 -- 同VA中的通道掩码 */
} ywfpa_SegmentInfo;

/* 媒体段 -- 一段媒体 */
typedef struct _ywfpa_SegmentUpdated {
    bool has_cmd_header;
    ywfpa_PkgHeader cmd_header; /* 包含 Header 消息 */
    bool has_seg_info;
    ywfpa_SegmentInfo seg_info; /* 媒体段信息 */
} ywfpa_SegmentUpdated;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ywfpa_CmdId_MIN ywfpa_CmdId_CmdNA
#define _ywfpa_CmdId_MAX ywfpa_CmdId_CmdSegmentUpdated
#define _ywfpa_CmdId_ARRAYSIZE ((ywfpa_CmdId)(ywfpa_CmdId_CmdSegmentUpdated+1))







/* Initializer values for message structs */
#define ywfpa_PkgHeader_init_default             {0, 0, 0, 0, 0, 0}
#define ywfpa_DevAdded_init_default              {false, ywfpa_PkgHeader_init_default, 0}
#define ywfpa_DevRemoved_init_default            {false, ywfpa_PkgHeader_init_default, 0}
#define ywfpa_SegmentInfo_init_default           {0, 0, 0, 0, 0, 0}
#define ywfpa_SegmentUpdated_init_default        {false, ywfpa_PkgHeader_init_default, false, ywfpa_SegmentInfo_init_default}
#define ywfpa_PkgHeader_init_zero                {0, 0, 0, 0, 0, 0}
#define ywfpa_DevAdded_init_zero                 {false, ywfpa_PkgHeader_init_zero, 0}
#define ywfpa_DevRemoved_init_zero               {false, ywfpa_PkgHeader_init_zero, 0}
#define ywfpa_SegmentInfo_init_zero              {0, 0, 0, 0, 0, 0}
#define ywfpa_SegmentUpdated_init_zero           {false, ywfpa_PkgHeader_init_zero, false, ywfpa_SegmentInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ywfpa_PkgHeader_magic_tag                1
#define ywfpa_PkgHeader_cmd_tag                  2
#define ywfpa_PkgHeader_seq_tag                  3
#define ywfpa_PkgHeader_seq_org_tag              4
#define ywfpa_PkgHeader_rc_tag                   5
#define ywfpa_PkgHeader_context_tag              6
#define ywfpa_DevAdded_cmd_header_tag            1
#define ywfpa_DevAdded_dev_id_tag                2
#define ywfpa_DevRemoved_cmd_header_tag          1
#define ywfpa_DevRemoved_dev_id_tag              2
#define ywfpa_SegmentInfo_dev_id_tag             1
#define ywfpa_SegmentInfo_seg_id_tag             2
#define ywfpa_SegmentInfo_begin_time_tag         3
#define ywfpa_SegmentInfo_end_time_tag           4
#define ywfpa_SegmentInfo_media_type_mask_tag    5
#define ywfpa_SegmentInfo_ch_mask_tag            6
#define ywfpa_SegmentUpdated_cmd_header_tag      1
#define ywfpa_SegmentUpdated_seg_info_tag        2

/* Struct field encoding specification for nanopb */
#define ywfpa_PkgHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  magic,             1) \
X(a, STATIC,   SINGULAR, FIXED32,  cmd,               2) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               3) \
X(a, STATIC,   SINGULAR, UINT32,   seq_org,           4) \
X(a, STATIC,   SINGULAR, INT32,    rc,                5) \
X(a, STATIC,   SINGULAR, UINT32,   context,           6)
#define ywfpa_PkgHeader_CALLBACK NULL
#define ywfpa_PkgHeader_DEFAULT NULL

#define ywfpa_DevAdded_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cmd_header,        1) \
X(a, STATIC,   SINGULAR, UINT32,   dev_id,            2)
#define ywfpa_DevAdded_CALLBACK NULL
#define ywfpa_DevAdded_DEFAULT NULL
#define ywfpa_DevAdded_cmd_header_MSGTYPE ywfpa_PkgHeader

#define ywfpa_DevRemoved_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cmd_header,        1) \
X(a, STATIC,   SINGULAR, UINT32,   dev_id,            2)
#define ywfpa_DevRemoved_CALLBACK NULL
#define ywfpa_DevRemoved_DEFAULT NULL
#define ywfpa_DevRemoved_cmd_header_MSGTYPE ywfpa_PkgHeader

#define ywfpa_SegmentInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dev_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   seg_id,            2) \
X(a, STATIC,   SINGULAR, UINT32,   begin_time,        3) \
X(a, STATIC,   SINGULAR, UINT32,   end_time,          4) \
X(a, STATIC,   SINGULAR, UINT32,   media_type_mask,   5) \
X(a, STATIC,   SINGULAR, UINT32,   ch_mask,           6)
#define ywfpa_SegmentInfo_CALLBACK NULL
#define ywfpa_SegmentInfo_DEFAULT NULL

#define ywfpa_SegmentUpdated_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cmd_header,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  seg_info,          2)
#define ywfpa_SegmentUpdated_CALLBACK NULL
#define ywfpa_SegmentUpdated_DEFAULT NULL
#define ywfpa_SegmentUpdated_cmd_header_MSGTYPE ywfpa_PkgHeader
#define ywfpa_SegmentUpdated_seg_info_MSGTYPE ywfpa_SegmentInfo

extern const pb_msgdesc_t ywfpa_PkgHeader_msg;
extern const pb_msgdesc_t ywfpa_DevAdded_msg;
extern const pb_msgdesc_t ywfpa_DevRemoved_msg;
extern const pb_msgdesc_t ywfpa_SegmentInfo_msg;
extern const pb_msgdesc_t ywfpa_SegmentUpdated_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ywfpa_PkgHeader_fields &ywfpa_PkgHeader_msg
#define ywfpa_DevAdded_fields &ywfpa_DevAdded_msg
#define ywfpa_DevRemoved_fields &ywfpa_DevRemoved_msg
#define ywfpa_SegmentInfo_fields &ywfpa_SegmentInfo_msg
#define ywfpa_SegmentUpdated_fields &ywfpa_SegmentUpdated_msg

/* Maximum encoded size of messages (where known) */
#define YWFPA_YW_FPA_PB_H_MAX_SIZE               ywfpa_SegmentUpdated_size
#define ywfpa_DevAdded_size                      47
#define ywfpa_DevRemoved_size                    47
#define ywfpa_PkgHeader_size                     39
#define ywfpa_SegmentInfo_size                   36
#define ywfpa_SegmentUpdated_size                79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
